"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { useRouter } from 'next/navigation'

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter()
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>FİRST LAYOUT JS</div>
        <div>Sidebar</div>
        <hr />
        {children}
        <hr />
        <div>
          <button type="button" onClick={() => router.push('/')}>
            Back
          </button>
        </div>
        <div>Footer</div>
      </body>
    </html>
  );
}
